export default [
    { title: "Inception", genre: "Sci-Fi" },
    { title: "The Dark Knight", genre: "Action" },
    { title: "Forrest Gump", genre: "Drama" },
    { title: "Titanic", genre: "Romance" },
    { title: "The Godfather", genre: "Crime" },
    { title: "The Matrix", genre: "Sci-Fi" },
    { title: "Pulp Fiction", genre: "Crime" },
    { title: "The Shawshank Redemption", genre: "Drama" },
    { title: "Fight Club", genre: "Drama" },
    { title: "Star Wars: A New Hope", genre: "Sci-Fi" },
    { title: "Jurassic Park", genre: "Adventure" },
    { title: "The Avengers", genre: "Action" },
    { title: "Back to the Future", genre: "Sci-Fi" },
    { title: "Gladiator", genre: "Action" },
    { title: "Saving Private Ryan", genre: "War" },
    { title: "Avatar", genre: "Sci-Fi" },
    { title: "Toy Story", genre: "Animation" },
    { title: "The Lion King", genre: "Animation" },
    { title: "The Silence of the Lambs", genre: "Thriller" },
    { title: "Schindler's List", genre: "Historical Drama" },
    { title: "Braveheart", genre: "Historical" },
    { title: "The Terminator", genre: "Sci-Fi" },
    { title: "Alien", genre: "Horror" },
    { title: "Rocky", genre: "Sports" },
    { title: "The Big Lebowski", genre: "Comedy" },
    { title: "Indiana Jones: Raiders of the Lost Ark", genre: "Adventure" },
    { title: "Harry Potter and the Sorcerer's Stone", genre: "Fantasy" },
    { title: "The Lord of the Rings: The Fellowship of the Ring", genre: "Fantasy" },
    { title: "The Exorcist", genre: "Horror" },
    { title: "Deadpool", genre: "Action" },
    { title: "The Hangover", genre: "Comedy" },
    { title: "Spider-Man: Into the Spider-Verse", genre: "Animation" },
    { title: "Finding Nemo", genre: "Animation" },
    { title: "Interstellar", genre: "Sci-Fi" },
    { title: "Mad Max: Fury Road", genre: "Action" },
    { title: "A Beautiful Mind", genre: "Biography" },
    { title: "Coco", genre: "Animation" },
    { title: "Wonder Woman", genre: "Action" },
    { title: "Frozen", genre: "Animation" },
    { title: "Guardians of the Galaxy", genre: "Sci-Fi" },
    { title: "The Prestige", genre: "Thriller" },
    { title: "Pirates of the Caribbean: The Curse of the Black Pearl", genre: "Adventure" },
    { title: "Doctor Strange", genre: "Fantasy" },
    { title: "Shrek", genre: "Animation" },
    { title: "It", genre: "Horror" },
    { title: "Logan", genre: "Action" },
    { title: "Django Unchained", genre: "Western" },
    { title: "The Social Network", genre: "Biography" },
    { title: "Up", genre: "Animation" },
    { title: "La La Land", genre: "Musical" },
    { title: "Black Panther", genre: "Action" },
    { title: "The Wolf of Wall Street", genre: "Biography" },
    { title: "12 Years a Slave", genre: "Historical Drama" },
    { title: "The Grand Budapest Hotel", genre: "Comedy" },
    { title: "The Revenant", genre: "Adventure" },
    { title: "The Hateful Eight", genre: "Western" },
    { title: "John Wick", genre: "Action" },
    { title: "Gravity", genre: "Sci-Fi" },
    { title: "Birdman", genre: "Drama" },
    { title: "The Imitation Game", genre: "Biography" },
    { title: "Whiplash", genre: "Drama" },
    { title: "Les Misérables", genre: "Musical" },
    { title: "The Girl with the Dragon Tattoo", genre: "Thriller" },
    { title: "Moonlight", genre: "Drama" },
    { title: "The Great Gatsby", genre: "Romance" },
    { title: "Her", genre: "Romance" },
    { title: "American Sniper", genre: "War" },
    { title: "Blade Runner 2049", genre: "Sci-Fi" },
    { title: "The Shape of Water", genre: "Fantasy" },
    { title: "Parasite", genre: "Thriller" },
    { title: "Knives Out", genre: "Mystery" },
    { title: "A Quiet Place", genre: "Horror" },
    { title: "1917", genre: "War" },
    { title: "Bohemian Rhapsody", genre: "Biography" },
    { title: "Once Upon a Time in Hollywood", genre: "Comedy" },
    { title: "Joker", genre: "Drama" },
    { title: "The Irishman", genre: "Crime" },
    { title: "Ford v Ferrari", genre: "Biography" },
    { title: "The King’s Speech", genre: "Biography" },
    { title: "Slumdog Millionaire", genre: "Drama" },
    { title: "The Hunger Games", genre: "Adventure" },
    { title: "Snowpiercer", genre: "Sci-Fi" },
    { title: "The Witch", genre: "Horror" },
    { title: "The Truman Show", genre: "Comedy" },
    { title: "V for Vendetta", genre: "Thriller" },
    { title: "The Departed", genre: "Crime" },
    { title: "Memento", genre: "Thriller" },
    { title: "The Pianist", genre: "Biography" },
    { title: "Life of Pi", genre: "Adventure" },
    { title: "Casino Royale", genre: "Action" },
    { title: "Kingsman: The Secret Service", genre: "Action" },
    { title: "Zootopia", genre: "Animation" },
    { title: "Arrival", genre: "Sci-Fi" },
    { title: "Shutter Island", genre: "Thriller" },
    { title: "The Pursuit of Happyness", genre: "Drama" },
    { title: "Inglourious Basterds", genre: "War" },
    { title: "The Greatest Showman", genre: "Musical" }
  ];
  